# encoding: utf-8


#FIXME: upstream/python: see HACK below
PYTHON_MODULES_SETUP = """\
*static*

# defaults:
# LIBDEST=$(SCRIPTDIR)/python$(VERSION)
# BINLIBDEST=$(LIBDIR)/python$(VERSION)
DESTLIB=$(LIBDEST)
MACHDESTLIB=$(BINLIBDEST)

# DESTPATH *always* empty!
# addtl entries *must* start with ':'
DESTPATH=
MACHDEPPATH=:plat-$(MACHDEP)
# add site-packages... even if missing
SITEPATH=:site-packages

# runtime prefix prepended to each entry
PYTHONPATH=$(DESTPATH)$(MACHDEPPATH)$(SITEPATH)

# core modules, *always* static
_codecs _codecsmodule.c
_sre _sre.c
_symtable symtablemodule.c
_weakref _weakref.c
errno errnomodule.c
posix posixmodule.c
pwd pwdmodule.c
zipimport zipimport.c

#HACK: eliminates path oddities before distutils chokes
CONFINCLUDEDIR= $(abspath $(exec_prefix)/include)
LIBDIR=         $(abspath ${exec_prefix}/lib)
BINDIR=         $(abspath ${exec_prefix}/bin)
MANDIR=         $(abspath ${datarootdir}/man)
INCLUDEDIR=     $(abspath ${prefix}/include)
SCRIPTDIR=      $(abspath $(prefix)/lib)
datarootdir=    $(abspath ${prefix}/share)

# AUTOGENERATED...
"""
